### ISSUE TITLE
some editor ?

### ISSUE THREAD

**Issue by miroi** [dev-cafe/docker-images#3]
Hi Roberto,

I downloaded your nice docker, https://hub.docker.com/r/devcafe/cmake-cookbook_circleci_ubuntu16.04-pgi18.4 , to try PG compilers.

However, I am missing there editor - no nano, vim, kate ... to be able to work interactively. 

Would you please provide some ? Or I shall add it by myself...

**Comment by robertodr** [comment]
The `circleci` images were made for use on CI servers, where there is no need for editors. There are files to build images for end-users (https://github.com/dev-cafe/docker-images/tree/master/cmake-cookbook_ubuntu16.04-pgi17.4) but I stopped uploading them to Docker Hub some time ago. You can modify those at will.

**Comment by miroi** [comment]
OK, in between I got answer from  https://superuser.com/a/1474828/387617 ; thanks for your nice work, I plan do some modifications (editor for the purpose of editing files in docker's interactive session). 

Closing this ticket.
