### ISSUE TITLE
devcafe/ubuntu18.04-gcc7.3.0-openmpi2.1.0-mkl2017.4.239:latest - initialization of  MKL

### ISSUE THREAD

**Issue by miroi** [dev-cafe/docker-images#4]
Hi Roberto !

I just downloaded https://hub.docker.com/r/devcafe/ubuntu18.04-gcc7.3.0-openmpi2.1.0-mkl2017.4.239 ,  and I am trying to make MKL running.
I did 
~~~
7ce34985$ . ./mklvars.sh intel64        

ERROR: architecture is not defined. Accepted values: ia32, intel64, mic
~~~

Any help, please ?

**Comment by miroi** [comment]
I think I solved it: the key is the **bash** shell:
~~~
udocker run devcafe/ubuntu18.04-gcc7.3.0-openmpi2.1.0-mkl2017.4.239:latest  bash
mightybuilder@lxbk0197:~$ . /opt/intel/mkl/bin/mklvars.sh intel64 ilp64
mightybuilder@lxbk0197:~$ echo $MKLROOT
/opt/intel/compilers_and_libraries_2017.5.239/linux/mkl
~~~

Comments ? You can also close this ticket, if nothing to be added.

**Comment by robertodr** [comment]
@miroi sorry for not replying before (the email notification was buried in the pile) I'm glad you managed to solve the issue, but I'm still puzzled as to why you couldn't find MKL in the first place. The entrypoint for the image *does source*  the `compilervars.sh` script [already](https://github.com/dev-cafe/docker-images/blob/master/ubuntu18.04-gcc7.3.0-openmpi2.1.0-mkl2017.4.239/entrypoint_source#L1-L2)

**Comment by miroi** [comment]
Ah, compilervars.sh is the key... maybe I did not check it before.

I think that upon activating bash one also activates compilervars.sh, so this issue could be irrelevant.

**Comment by robertodr** [comment]
It could be. I used the following command:
```
docker run -it devcafe/ubuntu18.04-gcc7.3.0-openmpi2.1.0-mkl2017.4.239:latest
```
and `echo $MKLROOT` printed the location of the library.
